### ISSUE TITLE
Implement a utility class to parse YAML configuration files

### ISSUE THREAD

**Issue by HerbertKoelman** [HerbertKoelman/cpp-atmi#24]
Propose a class to parse a YAML configuration file. The parsed data will be converted into key/value pairs. Each key is pa unique path to a value. A value is either a single value or multiple values separated by a sequence separator (for example white space).

This is the kind of yaml file it should be able to parse and convert into a map of key/value pairs:

```
#  Tuxedo client configuration file
# Client: atm/atmw

basedir: /home/herbert/

# Tuxedo onfiguration
tuxconfig:
  - /home/herbert/conf/ubbconfig.red.bin
  - /home/herbert/conf/ubbconfig.blue.bin

# Listens
network:
  - listen:
      - //0.0.0.0:2000
      - //0.0.0.0:2001

# Database
database:
  url: database://hostname:1521/monitoring
  user: dbuser
  password: A1Q2W3

# Queue Manager
mqseries:
  queuemanager: CLBPE
  hostname: etoile
  port: 141
  queues:
    - queries: LBP.OPO.Q
    - responses: LBP.OPO.R
  subscriptions:
    opposition:
      - notif.opo.reseau
        notif.opo.bo
```

The map should contain the following pairs:

```
root.basedir: /home/herbert/
root.database.password: A1Q2W3
root.database.url: database://hostname:1521/monitoring
root.database.user: dbuser
root.mqseries.hostname: etoile
root.mqseries.port: 141
root.mqseries.queuemanager: CLBPE
root.mqseries.queues.queries: LBP.OPO.Q
root.mqseries.queues.responses: LBP.OPO.R
root.mqseries.subscriptions.opposition: notif.opo.reseau notif.opo.bo 
root.network.listen: //0.0.0.0:2000 //0.0.0.0:2001 
root.tuxconfig: /home/herbert/conf/ubbconfig.red.bin /home/herbert/conf/ubbconfig.blue.bin 
```
